# Generated by Django 5.0 on 2024-03-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('portfolio_profile', models.FileField(upload_to='Portfolio Profile')),
                ('Details_photo', models.FileField(upload_to='Details Photos')),
                ('years', models.IntegerField()),
                ('based_expirience', models.CharField(max_length=288)),
                ('description', models.TextField()),
            ],
        ),
    ]
