# Generated by Django 5.0 on 2024-03-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Details_photo',
            new_name='Details_photo1',
        ),
        migrations.AddField(
            model_name='details',
            name='Details_photo2',
            field=models.FileField(default=1, upload_to='Details Photos'),
            preserve_default=False,
        ),
    ]
