# Generated by Django 5.0 on 2024-03-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_visibilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='visibilities',
            name='for_two_detail_image',
            field=models.IntegerField(default='0'),
        ),
    ]
