# Generated by Django 5.0 on 2024-03-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_visibilities_for_two_detail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='collaborations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=188)),
                ('description', models.TextField()),
            ],
        ),
    ]
