# Generated by Django 5.0 on 2024-03-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_collaborations'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborations',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
