# Generated by Django 5.0 on 2024-03-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_technolo'),
    ]

    operations = [
        migrations.CreateModel(
            name='prof_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=188)),
            ],
        ),
    ]
