# Generated by Django 5.0 on 2024-03-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_prof_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=88)),
                ('date1', models.IntegerField()),
                ('date2', models.IntegerField()),
                ('location', models.CharField(max_length=188)),
            ],
        ),
        migrations.CreateModel(
            name='expirience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=88)),
                ('date1', models.IntegerField()),
                ('date2', models.IntegerField()),
                ('location', models.CharField(max_length=188)),
            ],
        ),
    ]
