# Generated by Django 5.0 on 2024-03-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_education_expirience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date1',
            field=models.CharField(max_length=88),
        ),
        migrations.AlterField(
            model_name='education',
            name='date2',
            field=models.CharField(max_length=88),
        ),
        migrations.AlterField(
            model_name='expirience',
            name='date1',
            field=models.CharField(max_length=88),
        ),
        migrations.AlterField(
            model_name='expirience',
            name='date2',
            field=models.CharField(max_length=88),
        ),
    ]
