# Generated by Django 5.0 on 2024-03-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_alter_education_date1_alter_education_date2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=188)),
                ('description', models.CharField(max_length=388)),
            ],
        ),
    ]
