# Generated by Django 5.0 on 2024-03-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_servicess'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_banner', models.FileField(max_length=188, upload_to='Projects')),
                ('title', models.CharField(max_length=88)),
                ('link', models.CharField(max_length=88)),
                ('description', models.TextField()),
                ('highlight', models.IntegerField(choices=[('0', 'Hide to portfolio'), ('1', 'Hide to Index'), ('1', 'Visible to All')], default=3)),
            ],
        ),
    ]
