# Generated by Django 5.0 on 2024-03-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_alter_projects_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='highlight',
            field=models.CharField(choices=[('hide1', 'Hide to portfolio'), ('hide2', 'Hide to Index'), ('open', 'Visible to All')], default='open', max_length=28),
        ),
    ]
