# Generated by Django 5.0 on 2024-03-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_alter_projects_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='googlemap',
            field=models.CharField(max_length=1888, null=True),
        ),
    ]
