# Generated by Django 5.0 on 2024-03-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_details_googlemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='extenal_contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('email', 'Email'), ('number', 'Phone Number'), ('normal', 'Normal')], max_length=50)),
            ],
        ),
    ]
