# Generated by Django 5.0 on 2024-03-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_extenal_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('fa-facebook', 'facebooks'), ('fa-gitlab', 'Git Lab'), ('fa-github', 'Git Hub'), ('fa-messenger', 'Messenger'), ('fa-twitter', 'Twitter'), ('fa-google', 'Google'), ('fa-linkedin', 'LinkedIn'), ('fa-youtube', 'Youtube'), ('fa-instagram', 'Instagram'), ('fa-pinterest', 'Pinterest'), ('fa-snapchat-ghost', 'Snapchat Ghost'), ('fa-skype', 'Skype'), ('fa-android', 'Andriod'), ('fa-dribbble', 'Dribble'), ('fa-vimeo', 'Vimeo'), ('fa-tumblr', 'Tumblr'), ('fa-vine', 'Vine'), ('fa-foursquare', 'Foursquare'), ('fa-stumbleupon', 'Stumbleupon'), ('fa-flickr', 'Flickr'), ('fa-yahoo', 'Yahoo'), ('fa-soundcloud', 'Soundcloud'), ('fa-reddit', 'Reddit'), ('fa-rss', 'Rss')], max_length=50)),
                ('link', models.CharField(max_length=188)),
            ],
        ),
    ]
