# Generated by Django 5.0 on 2024-03-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_social_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='galleries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(max_length=188, upload_to='Gallery')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('hide', 'Hide'), ('visible', 'Visible')], max_length=50)),
            ],
        ),
    ]
