# Generated by Django 5.0 on 2024-03-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_galleries_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=188)),
                ('email', models.CharField(max_length=188)),
                ('subject', models.CharField(max_length=188)),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('viewed', 'viewed'), ('unread', 'Unread')], default='unread', max_length=50)),
            ],
        ),
    ]
