# Generated by Django 5.0 on 2024-03-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0022_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countUserCount', models.IntegerField(default=0)),
                ('countUserMonth', models.CharField(max_length=3)),
                ('countUserDay', models.CharField(max_length=2)),
                ('countUserYear', models.CharField(max_length=4)),
                ('order_month', models.IntegerField()),
            ],
        ),
    ]
